# Generated by Django 5.1.3 on 2025-01-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="audio",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="video",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="audio_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
