# Generated by Django 5.1.3 on 2025-01-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "journal",
            "0002_remove_journalentry_audio_remove_journalentry_photo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="audio_url",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="journal_audio/"),
        ),
    ]
